dist: bionic

branches:
  only:
    - master

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran fftw3 libfftw3-dev libnetcdf-dev libnetcdf-c++4 libnetcdf-c++4-dev cmake libboost-dev libopenmpi-dev openmpi-bin python3-pip
  - pip3 install --user numpy netcdf4

before_script:
  - mkdir build_dp_cpu
  - cd build_dp_cpu
  - cmake -DSYST=ubuntu ..
  - cd ..
  - mkdir build_dp_cpumpi
  - cd build_dp_cpumpi
  - cmake -DSYST=ubuntu -DUSEMPI=true ..
  - cd ..

script:
  - cd build_dp_cpu
  - make -j 4
  - cd ../build_dp_cpumpi
  - make -j 4
  - cd ../cases
  - python3 run_travis.py

notifications:
  slack: microhh:hA8nIix9Z34cn6uG8xnz8Uiu
