#!/bin/bash
#SBATCH -t 1-00:00:00
###SBATCH -t 1:00:00
#SBATCH -N 4
#SBATCH -n 96
#SBATCH --tasks-per-node 24
###SBATCH -p short
###SBATCH -p gpu_short
###SBATCH -p gpu

module purge
module load 2019
module load intel/2018b
module load netCDF/4.6.1-intel-2018b
module load netCDF-C++4/4.3.0-intel-2018b
module load CMake/3.12.1-GCCcore-7.3.0
module load FFTW/3.3.8-intel-2018b
module load Doxygen/1.8.14-GCCcore-7.3.0

source ~/virtualenv/firstMLP_intel_CPU/bin/activate #Note: to ensure consistent runs, actives virtual environment created with install_tensorflow_cpu_cartesius.sh.

#Build MicroHH on CPU node where run is executed for optimal performance
cd ../../config
cp cartesius.cmake default.cmake

cd ..

if [ -d "build_MPI" ]; then
    rm -r build_MPI
fi

mkdir build_MPI

cd build_MPI

cmake .. -DUSEMPI=TRUE
make -j

cd ../cases/moser600


if [ ! -L "microhh_MPI" ]; then
    ln -s ../../build_MPI/microhh microhh_MPI
fi

#Initialize and run MicroHH for specified case
srun ./microhh_MPI init moser600
srun ./microhh_MPI run moser600
