#!/bin/bash
#SBATCH -t 1:00:00
####SBATCH -t 3-00:00:00
#SBATCH -N 1
#SBATCH -p short

# To make sure all folders and files within the project space are created with write permission for the group:
umask g+w

#Load modules new environment
module purge
module load 2019
module load intel/2018b
module load netCDF/4.6.1-intel-2018b
module load netCDF-C++4/4.3.0-intel-2018b
module load CMake/3.12.1-GCCcore-7.3.0
module load cuDNN/7.6.3-CUDA-10.0.130
module load FFTW/3.3.8-intel-2018b
module load Doxygen/1.8.14-GCCcore-7.3.0

source ~/virtualenv/firstCNN_intel_CPU/bin/activate

cd ./MLP_selected #Ensure figures are stored in directory of MLP

python3 -u ../read_CNNsmagpredictions.py --prediction_file "./MLP_predictions.nc" --training_file '../../cases/moser600/training_data/training_data.nc' --smagorinsky_file '../comparison_smag/smagorinsky_fluxes.nc' --stats_file '../../cases/moser600/training_data/means_stdevs_allfields.nc' --make_plots --make_table --reconstruct_fields
