#!/bin/bash
#SBATCH -t 03:00:00
#SBATCH -N 1
####SBATCH -p short

module purge
module load 2019
module load intel/2018b
module load netCDF/4.6.1-intel-2018b
module load netCDF-C++4/4.3.0-intel-2018b
module load CMake/3.12.1-GCCcore-7.3.0
module load cuDNN/7.6.3-CUDA-10.0.130
module load Doxygen/1.8.14-GCCcore-7.3.0


source ~/virtualenv/firstMLP_intel_CPU/bin/activate

#Run main script
python3 Smagorinsky_main.py

