#!/bin/bash
#SBATCH -t 1-00:00:00
####SBATCH -t 02:00:00
#SBATCH -N 1
####SBATCH -n 48
####SBATCH -p short
####SBATCH  -p fat
####SBATCH -p gpu_short
####SBATCH -p gpu

#Load modules new environment
module purge
module load 2019
module load intel/2018b
module load netCDF/4.6.1-intel-2018b
module load netCDF-C++4/4.3.0-intel-2018b
module load CMake/3.12.1-GCCcore-7.3.0
module load cuDNN/7.6.3-CUDA-10.0.130
module load FFTW/3.3.8-intel-2018b
module load Doxygen/1.8.14-GCCcore-7.3.0

#Activate virtual environment created with install_tensorflow_cpu_cartesius.sh (stored in config directory)
source ~/virtualenv/firstMLP_intel_CPU/bin/activate

##Create directory to store training data, remove it first if it already exists
#if [ -d "../cases/moser600/training_data" ]; then
#    rm -r ../cases/moser600/training_data
#fi
#
#mkdir ../cases/moser600/training_data

python3 main_training.py

echo 'finished'
